name: "Newman Tests"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run POSTMAN collection
        run: newman run QABackendTesting.postman_collection.json -e TodoistEnvironment.postman_environment.json
